### ISSUE TITLE
its not working for me

### ISSUE THREAD

**Issue by MapleWaffles** [naelstrof/VRPlayspaceMover#21]

**Comment by naelstrof** [comment]
Sorry, it works for me! You're going to have to give some more information if you want a more useful response.

**Comment by MapleWaffles** [comment]
The problem is that i dont know how to disable safety mode

**Comment by NotToBlame** [comment]
You're probably having the common issue after installing VR Input Emulator it runs in safety mode or has another error titled "Oops, something went wrong here" or something along those lines. If you haven't found out already you'll need to download a replacement DLL file [https://github.com/sharkyh20/OpenVR-InputEmulator/releases/tag/SteamVR-Fix](Which you can find here)
then just do as the page says
