### ISSUE TITLE
Please Make PlayspaceMover Compile-Only

### ISSUE THREAD

**Issue by CircuitLord** [naelstrof/VRPlayspaceMover#28]
So, this is becoming more and more of an issue everyday. New people everyday are learning that this program exists, many who may be little kids, and they share it around with their friends. 

More and more people are starting to fly around in VR games such as Rec Room, and I've even seen people using it to sneakily cheat in competitive games by lowering their hitbox into the ground.

While many good reasons for PlayspaceMover do exist, it should only be in the hands of people who are more responsible, and not little kids who abuse it.

Basically, my idea is to remove all the releases of PlayspaceMover from this repo and make it compile-only. This way, only people responsible enough to actually figure out how to compile it will be able to use it. Will people still share around their builds of it? Yes, they will. But those people will often be much more responsible and careful of who they share it with. And also, this will still be the first google search result.

I know my request is kind of demanding, and I understand if you'd rather not limit the future use of your tool like that, but the amount of people who use it is increasing, and it's going to get more and more out of hand.

Thanks,
-Circuit

**Comment by naelstrof** [comment]
You already need to use command line to use it. I'm not going to make people compile it, sorry.

Games should add detection for cheating themselves. I imagine people with bad legs might use this to move around in an app more "freely". Kinda like a VR wheelchair. I won't restrict access to VRPlayspaceMover if it might hit legitimate users too!

**Comment by CircuitLord** [comment]
Yeah, thinking about it from that point of view, it'd make it bad for the people who might really need it. Thanks anyways :)
