### ISSUE TITLE
--orbitTracker not working correctly.

### ISSUE THREAD

**Issue by Magukuu** [naelstrof/VRPlayspaceMover#4]
Wanted to try out the new --orbitTracker option but it doesn't really seem to do anything
![orbittracker](https://user-images.githubusercontent.com/39862623/40879386-529deed6-669f-11e8-8a9e-0b25af7dfabb.png)
.

**Comment by naelstrof** [comment]
Whoops! Yeah you have to enable `--fakeTrackers` as well in order to see the effect. I totally should make it auto-enable fakeTrackers if you specify it. My bad!

**Comment by Magukuu** [comment]
Alright! I'll try it out when i hop on VR next time. 👍

**Comment by naelstrof** [comment]
New release auto-enables `--fakeTrackers` if you specify `--orbitTracker`.
Thanks for the report!
