### ISSUE TITLE
Valve index button mapping

### ISSUE THREAD

**Issue by potatoE2** [naelstrof/VRPlayspaceMover#40]
The default button mapping for index controllers are bound to both B buttons and there is no way to reset the playspace without closing the software. Is there a way to re-map the controls for index?

**Comment by naelstrof** [comment]
You just have to specify the button IDs in the command line. You might want
to look at advancedvr settings. Afaik they include a playspacemover type
feature

**Comment by naelstrof** [comment]
Yeah this is the one: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings

> Advanced Space Features: gravity, space-turn, and space-drag

It might work more to your liking!

**Comment by potatoE2** [comment]
Ah ok thanks I'll give this a shot!
