### ISSUE TITLE
[Suggestion] Readme add - Run as admin if getting error

### ISSUE THREAD

**Issue by OneVoltTen** [naelstrof/VRPlayspaceMover#5]
```
Looking for SteamVR...Success!
Looking for VR Input Emulator...
Failed to connect to open vr input emulator, ensure you've installed it. If you have, try running this fix: https://drive.google.com/open?id=1Gn3IOm6GbkINplbEenu0zTr3DkB1E8Hc
```
Resolved after running PlayspaceMover.exe AND steam.exe as admin - perhaps add it to the readme to avoid confusion, thanks for making such a great program!

**Comment by LiraLamine** [comment]
Had the same issue, but running as admin did not help. Instead, it just endlessly looks for the VR Input Emulator and never gives an error message.

**Comment by zoth138** [comment]
Running as admin did not fix the issue.

**Comment by OneVoltTen** [comment]
@LiraLamine If you run playspacemover as admin you need to also run the steam.exe as admin .
